

services:
  node-app:
    build:
      context: .
    container_name: be-app
    environment:
      DATABASE_URL: "postgresql://postgres:filmy2024@172.17.0.1:5432/fimlydb_2024?schema=public"
      REDIS_HOST: "172.17.0.1"
    # command: ["npm", "run", "start:prod"]
    
    ports: 
    - "3000:3000"
    depends_on:
    - postgresql
    - redis


  postgresql:
    image: postgres:17
    container_name: pgdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: filmy2024
      POSTGRES_DB: fimlydb_2024
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis-app
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  
  ngrok-service-2:
    image: wernight/ngrok
    container_name: ngrok_service_2
    depends_on:
      - node-app
    command: "ngrok http host.docker.internal:8000"
    environment:
      NGROK_AUTHTOKEN: "2NhDgNikurKmfP5Tz2j4vi2MCQs_2wCC5XgTkXBFZtR8MwdHB"
    ports:
      - "4041:4040"

volumes:
  postgres_data:
  redis_data: