

services:
  node-app:
    build:
      context: .
    container_name: be-app
    environment:
      DATABASE_URL: "postgresql://postgres:filmy2024@postgresql:5432/fimlydb_2024?schema=public"
      REDIS_HOST: "redis"
    # command: ["npm", "run", "start:prod"]
    
    ports: 
    - "3000:3000"
    depends_on:
    - postgresql
    - redis


  postgresql:
    image: postgres:17
    container_name: pgdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: filmy2024
      POSTGRES_DB: fimlydb_2024
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis-app
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: